# Equirectangular model for Intel RealSense D435 (work in progress)

#==============#
# Camera Model #
#==============#

Camera:
  name: "Intel RealSense D435"
  setup: "RGBD"
  model: "equirectangular"

  fps: 60.0
  cols: 640
  rows: 480

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800
  mask_rectangles:
    - [0.0, 1.0, 0.0, 0.1]
    - [0.0, 1.0, 0.84, 1.0]
    - [0.0, 0.2, 0.7, 1.0]
    - [0.8, 1.0, 0.7, 1.0]

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.95
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

#=========================#
# LoopDetector Parameters #
#=========================#

LoopDetector:
  enabled: true
  reject_by_graph_distance: true
  min_distance_on_graph: 50
