# Equirectangular model for Intel RealSense D435 (work in progress)

#==============#
# Camera Model #
#==============#

Camera:
  name: "Intel RealSense D435"
  setup: "RGBD"
  model: "perspective"

  fx: 585.75607095
  fy: 585.75607095
  cx: 320.5
  cy: 240.5

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

  fps: 30.0
  cols: 640
  rows: 480
  focal_x_baseline: 40.0
  depth_threshold: 40.0

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Tracking:
  margin_local_map_projection: 10.0

Preprocessing:
  min_size: 800
  depthmap_factor: 5000.0

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.07471049682
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

#=========================#
# LoopDetector Parameters #
#=========================#

LoopDetector:
  enabled: true
  reject_by_graph_distance: true
  min_distance_on_graph: 50
